# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Mozhi installation tasks
  when: mozhi_enabled | bool
  tags:
    - setup-all
    - setup-mozhi
    - install-all
    - install-mozhi
  block:
    - name: Validate Mozhi configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Mozhi
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Mozhi uninstallation tasks
  when: not mozhi_enabled | bool
  tags:
    - setup-all
    - setup-mozhi
  block:
    - name: Uninstall Mozhi
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
