# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required Mozhi settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - mozhi_uid
    - mozhi_gid
    - mozhi_hostname
    - mozhi_path_prefix
    - mozhi_container_network

- name: Run if Traefik is enabled
  when: mozhi_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Mozhi Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - mozhi_container_labels_traefik_hostname
        - mozhi_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `mozhi_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if mozhi_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          mozhi_container_labels_traefik_path_prefix (`{{ mozhi_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/mozhi`).
      when: "mozhi_container_labels_traefik_path_prefix != '/' and mozhi_container_labels_traefik_path_prefix[-1] == '/'"
